name: Python Timetable updater

on:
  schedule:
    - cron: "0 0/3 * * *"
  workflow_dispatch:


jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python updater.py
      - name: Commit and Push
        id: commit
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          if [[ -n "$(git status --porcelain timetable.json)" ]]; then
            git add timetable.json
            timestamp=$(date +"%Y/%m/%d %H:%M:%S")
            git commit -m "GitHub Actions UTC ${timestamp}"
            branch_name="${GITHUB_REF#refs/heads/}"
            git push origin HEAD:${branch_name}
          fi